concrete = [
    "white_concrete",
    "light_gray_concrete",
    "gray_concrete",
    "black_concrete",
    "brown_concrete",
    "red_concrete",
    "orange_concrete",
    "yellow_concrete",
    "lime_concrete",
    "green_concrete",
    "cyan_concrete",
    "light_blue_concrete",
    "blue_concrete",
    "purple_concrete",
    "magenta_concrete",
    "pink_concrete"
]
concretePowder = [
    "white_concrete_powder",
    "light_gray_concrete_powder",
    "gray_concrete_powder",
    "black_concrete_powder",
    "brown_concrete_powder",
    "red_concrete_powder",
    "orange_concrete_powder",
    "yellow_concrete_powder",
    "lime_concrete_powder",
    "green_concrete_powder",
    "cyan_concrete_powder",
    "light_blue_concrete_powder",
    "blue_concrete_powder",
    "purple_concrete_powder",
    "magenta_concrete_powder",
    "pink_concrete_powder"
]
wool = [
    "white_wool",
    "light_gray_wool",
    "gray_wool",
    "black_wool",
    "brown_wool",
    "red_wool",
    "orange_wool",
    "yellow_wool",
    "lime_wool",
    "green_wool",
    "cyan_wool",
    "light_blue_wool",
    "purple_wool",
    "magenta_wool",
    "pink_wool"
]
terracotta = [
    "white_terracotta",
    "light_gray_terracotta",
    "gray_terracotta",
    "black_terracotta",
    "brown_terracotta",
    "red_terracotta",
    "orange_terracotta",
    "yellow_terracotta",
    "lime_terracotta",
    "green_terracotta",
    "cyan_terracotta",
    "light_blue_terracotta",
    "blue_terracotta",
    "purple_terracotta",
    "magenta_terracotta",
    "pink_terracotta"
]
glazedTerracotta = [
    "white_glazed_terracotta",
    "light_gray_glazed_terracotta",
    "gray_glazed_terracotta",
    "black_glazed_terracotta",
    "brown_glazed_terracotta",
    "red_glazed_terracotta",
    "orange_glazed_terracotta",
    "yellow_glazed_terracotta",
    "lime_glazed_terracotta",
    "green_glazed_terracotta",
    "cyan_glazed_terracotta",
    "light_blue_glazed_terracotta",
    "blue_glazed_terracotta",
    "purple_glazed_terracotta",
    "magenta_glazed_terracotta",
    "pink_glazed_terracotta"
]